version: "3.9" # optional since v1.27.0
services:
  client:
    build: ./client/
    container_name: grading-site-client
    ports:
      - "8080:8080"
    volumes:
      - ./client/:/app/
      - node_modules:/app/node_modules/
    environment:
      - VUE_APP_API_ENDPOINT=http://localhost:5000
  server:
    build: ./server/
    container_name: grading-site-api
    ports:
      - "5000:5000"
    volumes:
      - ./server/:/home/worker/code/
      - venv:/home/worker/code/venv/
volumes:
  venv: {}
  node_modules: {}
